# Generated by Django 3.1.3 on 2021-08-06 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
