# Generated by Django 3.1.3 on 2021-08-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
