# Generated by Django 3.1.3 on 2021-08-06 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='add1link',
            field=models.CharField(default='addressl line 1', max_length=200),
        ),
        migrations.AddField(
            model_name='orderer',
            name='add2link',
            field=models.CharField(default='addressl line 2', max_length=200),
        ),
    ]
