# Generated by Django 3.1.3 on 2021-08-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_orderer_landmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderer',
            name='landmark',
            field=models.CharField(default='direction from home to nearest Landmark', max_length=500),
        ),
    ]
