# Generated by Django 3.1.3 on 2021-08-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20210807_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='customerhousetype',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
