# Generated by Django 3.1.3 on 2021-08-10 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_orderer_customerhousetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='formsubmitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vacinated',
            field=models.IntegerField(default=0),
        ),
    ]
