# Generated by Django 3.1.3 on 2021-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_orderer_reslev'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderer',
            name='reslev',
            field=models.FloatField(default=2),
        ),
    ]
