# Generated by Django 3.1.3 on 2021-08-12 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20210812_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='omaplink',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
