# Generated by Django 3.1.3 on 2021-08-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_orderer_omaplink'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='done',
            field=models.FloatField(default=0),
        ),
    ]
