# Generated by Django 3.1.3 on 2021-08-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_auto_20210814_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='merit',
            field=models.IntegerField(default=1000),
        ),
    ]
