# Generated by Django 3.1.3 on 2021-08-14 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_customuser_merit'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderer',
            name='paymode',
            field=models.CharField(default='1', max_length=5),
        ),
    ]
