# Generated by Django 3.1.3 on 2021-10-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_auto_20210815_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agroproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('use', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
