# Generated by Django 3.1.3 on 2021-10-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_customuser_is_farmer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agroproduct',
            old_name='use',
            new_name='description',
        ),
        migrations.AddField(
            model_name='agroproduct',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='agroproduct',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
