# Generated by Django 3.1.3 on 2021-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_auto_20211010_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroproduct',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
