# Generated by Django 3.1.3 on 2021-10-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_auto_20211010_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agroproduct',
            old_name='image',
            new_name='product_image',
        ),
        migrations.AddField(
            model_name='agroproduct',
            name='sell_location',
            field=models.CharField(default='place where you want to sell', max_length=100),
        ),
    ]
