# Generated by Django 3.1.3 on 2021-10-11 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_auto_20211011_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroproduct',
            name='name',
            field=models.CharField(default='seller name', max_length=200),
        ),
    ]
