# Generated by Django 3.1.3 on 2021-10-11 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_auto_20211011_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agroproduct',
            name='product_image',
            field=models.ImageField(default='images/tst2.png', upload_to='images'),
        ),
    ]
