# Generated by Django 3.1.3 on 2021-10-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_auto_20211011_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='veg',
            field=models.BooleanField(default=False),
        ),
    ]
