# Generated by Django 3.1.3 on 2021-10-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='headline', max_length=100)),
                ('link', models.CharField(default='#', max_length=1000)),
                ('img', models.ImageField(default='static/images/default.jpg', upload_to='images')),
            ],
        ),
    ]
