# Generated by Django 3.1.3 on 2021-10-09 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='oneliner',
            field=models.CharField(default='oneliner', max_length=50),
        ),
    ]
