# Generated by Django 3.1.3 on 2021-10-09 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_oneliner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='oneliner',
        ),
    ]
