# Generated by Django 3.1.3 on 2021-08-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vform',
            name='dosecount',
            field=models.IntegerField(default=0),
        ),
    ]
