# Generated by Django 3.1.2 on 2021-10-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Croplist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(default='cropname', max_length=25)),
                ('crop_img', models.URLField()),
                ('state', models.CharField(default='indian state', max_length=15)),
                ('lat', models.FloatField(default=0)),
                ('log', models.FloatField(default=0)),
            ],
        ),
    ]
