# Generated by Django 3.1.3 on 2021-10-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diseasetypes',
            options={'ordering': ['dname']},
        ),
        migrations.AlterField(
            model_name='patientname',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
