# Generated by Django 3.1.3 on 2021-10-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0002_auto_20211010_0952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diseasetypes',
            old_name='patient',
            new_name='crop',
        ),
    ]
