# Generated by Django 3.1.2 on 2021-10-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disease', '0003_auto_20211010_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasetypes',
            name='symptoms',
            field=models.CharField(default='_', max_length=2000),
        ),
    ]
