# Generated by Django 3.1.3 on 2021-08-05 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryperson', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
